---
apiVersion: v1
kind: ConfigMap
metadata:
  name: existing-homepage-configmap
  namespace: homepage
data:
  settings.yaml: |
    headerStyle: boxed
  bookmarks.yaml: |
    {}
  widgets.yaml: |
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  services.yaml: |
    - My Apps:
      - Proxmox:
          icon: proxmox
          href: https://proxmox.home.arpa:8006
          description: Virtualization
      - Pi-hole:
          icon: pi-hole
          href: https://pihole.home.arpa/admin
          description: Network-wide Ad Blocking
      - Grafana:
          icon: grafana
          href: https://grafana.home.arpa/
          description: Analytics and Monitoring
      - Filebrowser:
          icon: filebrowser
          href: https://files.home.arpa
          description: File Manager
  kubernetes.yaml: |
    {}
  docker.yaml: |
    {}
