---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
        - name: filebrowser
          image: ghcr.io/gtsteffaniak/filebrowser:1.5.6-stable
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: data
              mountPath: /home/filebrowser/data
            - name: config-yaml
              mountPath: /home/filebrowser/data/config.yaml
              subPath: config.yaml
            - name: media
              mountPath: /srv
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: filebrowser-config
        - name: config-yaml
          configMap:
            name: filebrowser-config
        - name: media
          nfs:
            server: 192.168.0.200
            path: /mnt/data/media
